### PR TITLE
Create german translation

### PR DESCRIPTION
**Pull request by TheGunter24**
made a german translation
was more work then first believed :D 
not perfect yet, feel free to give feedback

### CODE REVIEW

**Comment by Bara** [comment]
Im Grunde brauchst du die Zeilen mit `#format` nicht mit reinpacken, dies wird von der englischen Übersetzung übernommen.  Als Beispiel wären die Übersetzungen von SourceMod.

You don't need to add the lines `#format`, this part are just required in the english translations. As example are the default translations by sourcemod.

**Comment by TheGunter24** [comment]
> You don't need to add the lines `#format`, this part are just required in the english translations. As example are the default translations by sourcemod.

ehh, ok, but it doesnt hurt right ?
would be some work :D

**Comment by Bara** [comment]
As long as it works, but in future changes it must be updated too.

**Comment by PwnK** [comment]
In case you dont want to delete every `#format` line by hand you can use this regular expression in notepad++ and replace it with nothing `\t\t\"#format\".*\r\n`

**Comment by TheGunter24** [comment]
> In case you dont want to delete every `#format` line by hand you can use this regular expression in notepad++ and replace it with nothing `\t\t\"#format\".*\r\n`

you are absolutly right ^^
i can use notepad tools, thx

**Comment by TheGunter24** [comment]
ive changed the "fr" trans too

**Comment by TheGunter24** [comment]
is ready to merge if someone would pls do it ^^
(just updated to fit match https://github.com/olokos/Surftimer-olokos/commit/87606996a0f8052c2d7c8cacf769a833f2988396)

**Pull request merged**
