### PR TITLE
Added Cvar to disallow !pause

### PR DESCRIPTION
**Pull request by Moisty145**

### CODE REVIEW

**Comment by 13ace37** [comment]
why? there is ck_pause ?

**Comment by LubricantJam** [comment]
I'll explain why this is, it's due to some people running blacky's movement anticheat the !pause due to the MoveType_None that it uses. It's typically very situational, hence the cvar.

**Comment by 13ace37** [comment]
Just remove the whole command. It's not working correctly anyway.

**Comment by LubricantJam** [comment]
Didn't know if people wanted it to be kept, hence why we added the cvar for it. If people want it removed, we can do so.

**Comment by 13ace37** [comment]
But I can't see any changes to 
```cpp
	if (GetConVarBool(g_hPauseServerside) == false && client != g_RecordBot && client != g_BonusBot)
		{
			CPrintToChat(client, "%t", "Pause1", g_szChatPrefix);
			return;
		}
```

It's also returning, why would you add a second cvar to do the same thing?

**Comment by sneak-it** [comment]
> I'll explain why this is, it's due to some people running blacky's movement anticheat the !pause due to the MoveType_None that it uses. It's typically very situational, hence the cvar.

I have a similar function in my AC - I will PR in a new native that returns if a client is paused. You will then be able to use this native in the AC to ignore players that are paused.

**Comment by Moisty145** [comment]
Didin't realize there was a lready a cvar for this. Why is it placed so late though? surely if you disallow pausing you might as well stop it at the start?

**Comment by olokos** [comment]
I'm not sure what's the final decision about mering cvar to allow/disallow pause is, but it looks good to me.
Second commit is definitely useful, so I'm merging this.

**Pull request merged**
