### PR TITLE
remove trails chroma from timer

### PR DESCRIPTION
**Pull request by 13ace37**
https://github.com/olokos/Surftimer-olokos/issues/36#issuecomment-615484862

### CODE REVIEW

**Comment by Bara** [comment]
Would make both files obsolete, so you can remove them too

**Comment by sneak-it** [comment]
As long as it compiles without any warnings/errors, looks great! 👍

**Comment by olokos** [comment]
Seems like there are some conflicts, quite possibly because of the recent merges of pull requests i just did.

Could you confirm it works fine and causes no issues with current code? 
@13ace37

**Comment by Bara** [comment]
I can't see the conflicts, but should comes from the enumStrucs merge because I modified the enum array.

**Comment by olokos** [comment]
Yeah, exactly what I thought, but I'm on mobile, so can't resolve the conflict in this PR myself, so I can't merge it myself, until conflicts are resolved.

**Comment by 13ace37** [comment]
Never compiled it btw. I think there is still a cvar left.

**Pull request merged**
